### PR TITLE
CR056: add Branding to JourneyPatternInfoGroup

### PR DESCRIPTION
**Pull request by haeckerbaer**
Change Request for the addition of the NeTEx "Branding" model to all SIRI functional services. See documentation in the basecamp:
[Siri_CR_056_Branding.doc](https://3.basecamp.com/3256016/buckets/9672657/uploads/1952408176)

### CODE REVIEW

**Comment by Aurige** [comment]
I understand now why you added TypeOfValue in the KeyList CR: TypeOfValue  is required for Branding. However since only Branding uses it, I would advise to move the addition of TypeOfValue here !

**Comment by hennoit** [comment]
The simpleType "BrandingRefCodeType" should be called "BrandingCodeType", so that it is similar to (nearly) all other "xxxCodeType" structures in this file.

**Comment by haeckerbaer** [comment]
@hennoit 
Thanks for you input. I renamed it. 
However, I based the name on the LineRefCodeType example:

Should I change that to?
@Aurige I will look again whether I've misunderstood CR013 (the TypeOfValue part of it). I was under the impression that both, the KeyList and ValueSet/TypeOfValue structure, were requested. What do the other reviewers think about this?

**Comment by haeckerbaer** [comment]
Travis found a missing import for the new TypeOfValueGroup:
[Travis Build #23](https://travis-ci.com/SIRI-CEN/SIRI/builds/135440219)
Was added in the new commit.

**Comment by haeckerbaer** [comment]
As soon as [CR013 (add KeyList and TypesOfValue)](https://github.com/SIRI-CEN/SIRI/pull/11) is approved and merged, Travis CI Build will pass. Then this request can be merged too.

**Comment by hennoit** [comment]
> @hennoit
> Thanks for you input. I renamed it.
> However, I based the name on the LineRefCodeType example:
> 
> Should I change that to?

Indeed, LineRefCodeType seems to be the (only) exception in this file.
Changing it will probably break backwards compatibility? In that case we better leave it as it is.

**Pull request merged**
