### PR TITLE
(CR Siri-054) Update siri_datedVehicleJourney-v2.0.xsd

### PR DESCRIPTION
**Pull request by hennoit**
CR Siri-054: add optional elements ExtraCall and Cancellation to DatedCall

### CODE REVIEW

**Comment by haeckerbaer** [comment]
@hennoit Thanks for the PullRequest! Please see my review with comments.

**Comment by haeckerbaer** [comment]
See also the updated documentation of the Change Request in the basecamp:
[Siri_CR_054_Extra-and-Cancel-also-on-Calls-in-SIRI-PT.doc](https://3.basecamp.com/3256016/buckets/9672657/uploads/1952407676)

**Comment by Aurige** [comment]
I'm Ok (as agreed in Paris) with the change, however I think we need to be very clear about what it means in PT (it's obvious in ET but as explained in my comment in the excell file, PT is still about somethin planed). So the main point to clarify (can be in documentation and comments) it to what does extra/cancelled relates to:
- is it relative to the latest NeTEx (or scheduled information) transmited ?
- is it relative to a previous PT message ? and if so will the **Call** remain _extra/cancelled_ in possible future updates using PT ?
- does a **Call** marked _extra/cancelled_ in PT should also be marked _extra/cancelled_  in ET ?

**Comment by hennoit** [comment]
Replaced by #18  (so that changes are merged into integration branch first)

**Pull request closed without merging**
