### PR TITLE
Switch travis to github actions

### PR DESCRIPTION
**Pull request by skinkie**

### CODE REVIEW

**Comment by skinkie** [comment]
Don't apply this until you are done with the rest. Otherwise the rest should be rebased.

**Comment by ue71603** [comment]
@skinkie  With rest you mean the other issues? Will test it tomorrow.

**Comment by skinkie** [comment]
@ue71603 all other pull requests, otherwise _they_ require a rebase, instead of this one.

**Review by ue71603 — APPROVED** [review]

**Review by sgrossberndt — DISMISSED** [review]

**Comment by sgrossberndt** [comment]
Two questions remain for this pull request:
* Should this pull request be made against `master` or `integration`?
* Should integration be added in [.github/workflows/ci.yml](https://github.com/SIRI-CEN/SIRI/pull/112/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f):
```
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
```

**Comment by skinkie** [comment]
Maybe integration then?

**Comment by ue71603** [comment]
@sgrossberndt @skinkie  @haeckerbaer : The PR seems to work now. Do we add this to integration? Then we can start rebasing....approvals needed

**Review by ue71603 — APPROVED** [review]

**Review by sgrossberndt — APPROVED** [review]

**Pull request merged**
