### PR TITLE
CR55: Structured Reason, Effect, Advice

### PR DESCRIPTION
**Pull request by hennoit**
See also the explanations and the proposed changes to the documentation on basecamp.

Note: This PR contains only the changes in te 'original' SIRI-SX structures. I will separately look at analogous additions to the PublishingActions proposed by the UmS group.

### CODE REVIEW

**Comment by haeckerbaer** [comment]
@hennoit 
In your pptx (https://3.basecamp.com/3256016/buckets/9672657/uploads/2486846070) you presented us the following changes:
image
It included the name change of element "ReasonName" to "ReasonText" as well as new elements AdviceText and ConditionText. However, in your commits you named them all "XXXName". Did we decide this in a SG7 Meeting because of backward compatibility? I'm not sure anymore, but I found your approach better (with XXXText). The ReasonName annotation for examples reads "Text explanation" in its first sentence.. We could also add ReasonText and mark ReasonName "deprecated" (plus your original names AdviceText etc.)

**Comment by haeckerbaer** [comment]
> See also the explanations and the proposed changes to the documentation on basecamp.
> 
> Note: This PR contains only the changes in te 'original' SIRI-SX structures. I will separately look at analogous additions to the PublishingActions proposed by the UmS group.

Did you have a look at the PublishingActions additions? Will there be another PullRequest or what are the next steps?
Regards A

**Comment by hennoit** [comment]
> @hennoit
> In your pptx (https://3.basecamp.com/3256016/buckets/9672657/uploads/2486846070) you presented us the following changes:
> image
> It included the name change of element "ReasonName" to "ReasonText" as well as new elements AdviceText and ConditionText. However, in your commits you named them all "XXXName". Did we decide this in a SG7 Meeting because of backward compatibility? I'm not sure anymore, but I found your approach better (with XXXText). The ReasonName annotation for examples reads "Text explanation" in its first sentence.. We could also add ReasonText and mark ReasonName "deprecated" (plus your original names AdviceText etc.)

We did not discuss this in detail during the SG7 meeting. I decided to for xxxName instead of xxxText because the value contained in these elements should just be a (few) short word(s), analogous to the enumeration values, and NOT a complete sentence. The complete sentence, built from the enumeration OR the xxxName is given in the 'defaultedText' elements at another level in the message (in the DescriptionGroup). See also the description in the proposed documentation changes (onBasecamp).
The use of xxxName next to the enumeration resembles the structure in many parts of NeTEx/SIRI, where elements have a 'Name' and a 'ShortCode' or 'ShortName'. Also for me xxxText suggests more a complete sentence (which is NOT the intention here) than xxxName.
But it is probably wise to change the wording in annotation - at least change "Text" to "Textual".

**Comment by hennoit** [comment]
> > See also the explanations and the proposed changes to the documentation on basecamp.
> > Note: This PR contains only the changes in te 'original' SIRI-SX structures. I will separately look at analogous additions to the PublishingActions proposed by the UmS group.
> 
> Did you have a look at the PublishingActions additions? Will there be another PullRequest or what are the next steps?
> Regards A

No time so far... 
My intention is indeed to put it in a pull request.

**Pull request merged**
