### PR TITLE
CR 71  New Modes Dynamic - siri_facility-v2.0.xsd

### PR DESCRIPTION
**Pull request by Aurige**
Change Request for the addition of realtime counting to the Facility Monitoring service. 
See documentation in the basecamp: [NewModes Dynamic CR71 v1.docx.doc ](https://3.basecamp.com/3256016/buckets/9672657/uploads/2445231426)

This CR is designed to allow the exchange of dynamic information for all new modes of transport including bike sharing, car sharing, etc. but also about all types of parking (bike, car, scooter, motorbike, etc.). as requested by the European Regulation.
One of the key expectations is to provide information about counted values: current number of available vehicles, current number of spaces available to bring back a vehicle or to park, etc. Another expectation is to be able to receive updated position (typically for free floating vehicles).
The SIRI Facility Monitoring (FM) service can easily be extended to provide such counted information related to the monitored facilities. 

The CR is not limited to bikes and cars but is generalised to any type of Vehicle (bike, car, scooter, motorbike, etc.) but also to seat availability (in Stop Places Areas/Point of Interest/Vehicles…) or any similar facility (lockers, audio guides etc.), and is also suitable for a simple Passenger Counting. It also covers some simple measurement (fuel available in a Refueling Equipment, current available power of a Charging Equipment, etc.).

_-This Pull Request requires **_TypeOfValue_** from **CR13** to be able to validate
-This version already intergrate some feedack from @hennoit 
-The previous mistaken direct commit to the integration branch has been reverted_

### CODE REVIEW

**Comment by hennoit** [comment]
Should there also be an "unknown" value in CountingTrendEnumeration? Or perhaps just write in the SIRI documentation that leaving out the optional "Trend" element means it is unknown?

In the annotation of CountedFeatureUnitEnumeration: "kiloWatt per hour" should be "kiloWatt-hour". As a physicist I would say that otherwise it means 'energy divided by time divided by time', while kWh is just 'energy'.   :-) 

Looking through the file I saw a number of typing errors in (mostly old) annotations. I will try to add a commit in which these have been corrected.

**Comment by hennoit** [comment]
Adding my own commit to your pull request doesn't work (at least, I cannot do it...), so I will attach my updated file to my review.

**Comment by mentzrh** [comment]
Hi,

   - Or perhaps just write in the SIRI documentation that leaving out the
   optional "Trend" element means it is unknown?

I think leaving out an optional element rather means “the value stays like
it was set in the  last message” than “the value is unknown”. At least this
is the default meaning of missing  optional fields in the VDV 453/454
standards.



Regards,

Roland



*Von:* Henno Willering <notifications@github.com>
*Gesendet:* Dienstag, 12. Mai 2020 18:15
*An:* SIRI-CEN/SIRI <SIRI@noreply.github.com>
*Cc:* mentzrh <hesse@mentz.net>; Review requested <
review_requested@noreply.github.com>
*Betreff:* Re: [SIRI-CEN/SIRI] CR 71 New Modes Dynamic -
siri_facility-v2.0.xsd (#43)



Should there also be an "unknown" value in CountingTrendEnumeration? Or
perhaps just write in the SIRI documentation that leaving out the optional
"Trend" element means it is unknown?

In the annotation of CountedFeatureUnitEnumeration: "kiloWatt per hour"
should be "kiloWatt-hour". As a physicist I would say that otherwise it
means 'energy divided by time divided by time', while kWh is just 'energy'.
:-)

Looking through the file I saw a number of typing errors in (mostly old)
annotations. I will try to add a commit in which these have been corrected.

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub
<https://github.com/SIRI-CEN/SIRI/pull/43#issuecomment-627444026>, or
unsubscribe

**Comment by haeckerbaer** [comment]
Travis Error is because the new PercentageType is still missing here. Will be solved with CR002 after I updated it according to the comments and Basecamp discussion on percentage (https://3.basecamp.com/3256016/buckets/9672657/messages/2666053029#__recording_2666459089).

**Comment by Aurige** [comment]
> 
> 
> Travis Error is because the new PercentageType is still missing here. Will be solved with CR002 after I updated it according to the comments and Basecamp discussion on percentage (https://3.basecamp.com/3256016/buckets/9672657/messages/2666053029#__recording_2666459089).

yes, this CR has dependencies with multiple others ...

**Pull request merged**
