### PR TITLE
CR077: Some alignments between SIRI documentation and SIRI xsd

### PR DESCRIPTION
**Pull request by kgrimme**
This pull request contains three modifications on the XSD to align with current SIRI documentation.

1. PtSituationBodyGroup\TemporalGroup\PublicationWindow is unbounded in documentation
PublicationWindow

2. PtConsequenceStructure\Period is unbounded in documentation
Period

3. AffectedStopDepartureGroup\DeparturePlatformName is unbounded in documentation
DeparturePlatformName

Differences were detected while working for VDV UMS.

Do I need to create CR in word on basecamp?

### CODE REVIEW

**Comment by tim-rivett** [comment]
Do I need to create CR in word on basecamp?
To keep the processes robust and changes properly tracked a CR should be created.

**Comment by Aurige** [comment]
> 
> 
> I would expect that analogously the ArrivalPlatformName in VehicleArrivalTimesGroup should also be unbounded. That should then also be corrected in the document.

I agree... so we keep things consist. 
Ok for the rest of the PR

**Comment by kgrimme** [comment]
Hi @hennoit,

> I would expect that analogously the ArrivalPlatformName in VehicleArrivalTimesGroup should also be unbounded. That should then also be corrected in the document.

As far as I can see the [current working copy](https://3.basecamp.com/3256016/buckets/9672657/vaults/2334360617) of the SIRI document states that element with a cardinality of 0:1.
image

In the siri_situationAffects-v2.0.xsd the definiton is according to the documentation:
`<xsd:element ref="ArrivalPlatformName" minOccurs="0"/>`

So as I don't know what you are referring to I did not change anything else as stated above (and in [CR document](https://3.basecamp.com/3256016/buckets/9672657/uploads/2566570354))

**Comment by hennoit** [comment]
> Hi @hennoit,
> 
> > I would expect that analogously the ArrivalPlatformName in VehicleArrivalTimesGroup should also be unbounded. That should then also be corrected in the document.
> 
> As far as I can see the [current working copy](https://3.basecamp.com/3256016/buckets/9672657/vaults/2334360617) of the SIRI document states that element with a cardinality of 0:1.
> image
> 
> In the siri_situationAffects-v2.0.xsd the definiton is according to the documentation:
> `<xsd:element ref="ArrivalPlatformName" minOccurs="0"/>`
> 
> So as I don't know what you are referring to I did not change anything else as stated above (and in [CR document](https://3.basecamp.com/3256016/buckets/9672657/uploads/2566570354))

My point is that in this case both the documentation and the xsd are wrong. Just like DeparturePlatformName is unbounded, also ArrivalPlatformName should be unbounded.

**Comment by haeckerbaer** [comment]
Hi @kgrimme  
Can you update the point from Hennoit's last comment?
Thanks

**Comment by haeckerbaer** [comment]
@hennoit @Aurige @kgrimme 
To be clear: Do we change xxPlatformName to unbounded in all Services or just ArrivalPlatformName in SX (to match the multiplicity of DeparturePlatformName there). xxPlatformName is 0:1 in all other Services.

**Comment by kgrimme** [comment]
@hennoit @haeckerbaer 
So, shall I modify the ArrivalPlatformName within the xsd and the document to reflect a cardinality of 0:*?
What about the mentioned VehicleArrivalTimesGroup ? Should that one also be modified to have a cardinality of 0:*?

Sorry for letting you wait for my answer. I am just back from my parental leave :)

**Comment by hennoit** [comment]
> @hennoit @Aurige @kgrimme
> To be clear: Do we change xxPlatformName to unbounded in all Services or just ArrivalPlatformName in SX (to match the multiplicity of DeparturePlatformName there). xxPlatformName is 0:1 in all other Services.

I think we should keep everything as consistent as possible. So let's make the multiplicity 0:1 in SX as well. This means no change in ArrivalPlatformName and revert the change in DeparturePlatformName. And correct the document as well: remove the 'unbounded' for DeparturePlatformName in SX.

**Comment by hennoit** [comment]
> @hennoit @haeckerbaer
> So, shall I modify the ArrivalPlatformName within the xsd and the document to reflect a cardinality of 0:_? What about the mentioned VehicleArrivalTimesGroup ? Should that one also be modified to have a cardinality of 0:_?
> 

The VehicleArrivalTimesGroup already has the correct cardinality (1:1). So no changes needed there!

**Comment by kgrimme** [comment]
@hennoit 
I removed the modified line from my proposed XSD so that the multiplicity of the DeparturePlatformName is now like before 0:1. I changed the [CR document on basecamp](https://3.basecamp.com/3256016/buckets/9672657/uploads/2566570354) instead.
Please approve my change request if the modifications of the XSD match your expectations.

@haeckerbaer 
I changed the [CR document on basecamp](https://3.basecamp.com/3256016/buckets/9672657/uploads/2566570354) so that it now states that the siri documentation has to be modified to reflect the state of the current xsd. Who will do those changes in the documentation for the DeparturePlatformName ?

**Comment by haeckerbaer** [comment]
@kgrimme 
Thanks! Can you update the working copy of the relevant documents (with a comment containing the CR/PullRequest number/title? You find the newest version [here](https://3.basecamp.com/3256016/buckets/9672657/vaults/1391437614).
Regards
A

**Comment by kgrimme** [comment]
@haeckerbaer 
I added a new version of the SIRI SX document and put a comment beside my changes refering to this pull request and the CR document.

**Pull request merged**
